---
#$1 = username
#$2 = user password
#$3 = server ip
#$4 = bucket name
#$5 = bucekt mem
#$6 = jason file
- hosts: localhost
  vars:
        user: admin
        pwd: password
        server_ip: 172.18.46.46
        bucket_name: test5
        bucket_mem: 100
        jason_file: /root/couchbase/test1.json
        bucket_type: couchbase  #couchbase or memcached
#        bucket_type: memcached
        bucket_port: 11230
        bucket_replica: 2
        bucket_ramsize: 100
        enable_flush: 1
        enable_index_replica: 1
        bucket_password: passw0rd
        backup_path: /root/couchbase/backup_couchbase/{{date_output.stdout}}

  tasks:
        - name: Backup Date name
          command: "date +%m_%d_%Y_%H"
          register: date_output

        - name: Creating Directory for Couchbase server
          file:
                path: "{{backup_path}}"
                state: directory

        - name: Creating backup of buckets doc from  Couchbase server
          #shell: "/opt/couchbase/bin/couchbase-cli bucket-delete -c {{server_ip}}:8081 -u {{user}} -p {{pwd}} --bucket={{bucket_name}}"
          #shell: "/opt/couchbase/bin/couchbase-cli bucket-delete -c {{server_ip}}:8081 -u {{user}} -p {{pwd}} --bucket={{item }}"
          shell: "/opt/couchbase/bin/cbbackup -u {{user}} -p {{pwd}}  http://{{server_ip}}:8081 {{backup_path}}"
          register: result1
          ignore_errors: True
          with_items:
                - test
                - test5
